### ISSUE TITLE
Problem with change to Source:

### ISSUE THREAD

**Issue by mwbringmann** [power-ras/libvpd#1]
Recently, you made a change to the .spec.in file of the packages libvpd / lsvpd / servicelog / libservicelog that is causing me a problem when I try to 'rpmbuild' the package.  You made a change like the following to each of them like,
 
-ExclusiveArch: ppc64 ppc ppc64le
-URL:           http://linux-diag.sf.net/lsvpd.html
-Source:                http://downloads.sourceforge.net/linux-diag/%{name}/%{version}/%{name}-%{version}.tar.gz
+ExclusiveArch:  ppc64 ppc ppc64le
+URL:            https://github.com/power-ras/libvpd
+Source:         https://github.com/power-ras/libvpd.git
 
which fails to build when I execute the directives for 'rpmbuild' like,
 
make dist-gzip
cp libvpd*gz /root/rpmbuild/SOURCEs
cp libvpd.spec /root/rpmbuild/SPECS
rpmbuild -ba /root/rpmbuild/SPECS/libvpd.spec
 
I get an error message like,
 
error: File /root/rpmbuild/SOURCES/libvpd-2.2.6.tar.gz: No such file or directory
 
I have replaced that like with one like,
 
Source: libvpd-%{version}.tar.gz
 
in order to get it to build.  What is your experience here?  According to the documentation for .spec files such as the one found here,
 
http://ftp.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html
 
the use of the 'libvpd.git' name has no real meaning here.
 
Thanks for your attention and assistance.

**Comment by shivaprasadbhat** [comment]
I Agree. will fix it.

**Comment by hegdevasant** [comment]
Thanks for pointing out @mwbringmann . I missed this when we migrated to github.

We have pushed fix to all the repos. Hence closing this issue.

-Vasant
