### ISSUE TITLE
Error in commit referencing target Source for rpmbuild

### ISSUE THREAD

**Issue by mwbringmann** [power-ras/libvpd#2]
Error in commit 2aa006543e82834d68821bda91c0dbc230272acf produces the following error message for rpmbuild:

[root@RHEL8 libvpd]# rpmbuild -ba ~/rpmbuild/SPECS/libvpd.spec
error: Bad source: /root/rpmbuild/SOURCES/v2.7.6.tar.gz: No such file or directory
[root@RHEL8 libvpd]# 

The commit includes the change,

-Source:                https://github.com/power-ras/lsvpd.git
+Source:                https://github.com/power-ras/%{name}/archive/v%{version}.tar.gz

which should have been,

-Source:                https://github.com/power-ras/libvpd.git
+Source:                https://github.com/power-ras/%{name}/archive/libvpd-%{version}.tar.gz

to match the file generated by the 'make dist-gzip' operation.

**Comment by hegdevasant** [comment]
Thanks for the report. I will fix it next week.

-Vasant
